language: python
cache: pip

python:
 - pypy
 - pypy3
 - 2.7
 - 3.4
 - 3.5
 - 3.6

sudo: false

install:
 - pip install -Ur requirements.txt
 - pip install -U coverage

script:
 - coverage run --source=fngbot ./test_fngbot.py

after_success:
 - pip install -U coveralls
 - coveralls

after_script:
 - coverage report
 - pip install -U flake8
 - flake8
matrix:
  fast_finish: true
