language: python

python:
 - pypy
 - pypy3
 - 2.7
 - 3.4
 - 3.5
 - 3.6

sudo: false

install:
 - pip install -r requirements.txt
 - pip install coverage

script:
 - coverage run --source=fngbot ./test_fngbot.py

after_success:
 - pip install coveralls
 - coveralls

after_script:
 - coverage report
 - pip install -U flake8
 - flake8
matrix:
  fast_finish: true
