language: python

python:
 - 2.6
 - 2.7
 - 3.2
 - 3.3
 - 3.4
 - pypy
 - pypy3

install:
 - pip install -r requirements.txt
 - pip install coverage
 - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip install unittest2; fi

script:
 - coverage run --source=fngbot ./test_fngbot.py

after_success:
 - pip install coveralls
 - coveralls

after_script:
 - coverage report
 - pip install pep8 pyflakes
 - pep8 --statistics --count *.py
 - pyflakes *.py | tee >(wc -l)

matrix:
  allow_failures:
    - python: 2.6
    - python: 3.2
    - python: pypy3
  fast_finish: true
